### PR TITLE
feat: added dock and stacking compositors

### PR DESCRIPTION
**Pull request by nesper8**
Created new section 'dock' and added nwg-dock 

Also created new section 'Stacking Compositor' and added hikari, labwc and liri-shell

### CODE REVIEW

**Comment by nesper8** [comment]
at the moment i only know about these three stacking compositors while Mir https://github.com/MirServer/mir is a set of libraries to make your own wayland compositor

**Comment by mpsq** [comment]
Thanks for your PR, it looks good! I will merge it soon. :tada:

Regarding mir, I would not include it to this website. So far we've been listing tools/libs that people can use out of the box. I would rather focus on users for the time being, developers will probably do research before attempting to build a new compositor.

**Comment by mpsq** [comment]
I like the new Dock session, would you mind moving [LavaLauncher](https://sr.ht/~leon_plickat/LavaLauncher/) there too?

**Comment by nesper8** [comment]
> I like the new Dock session, would you mind moving [LavaLauncher](https://sr.ht/~leon_plickat/LavaLauncher/) there too?

Done mate

**Comment by nesper8** [comment]
i apologize for the duplicate in the commit i made 
i also have added a logout prompt too with an entry of wlogout https://github.com/ArtsyMacaw/wlogout

**Comment by wiki-me** [comment]
It's probably worth mentioning [wayfire](https://wayfire.org/), it seems  more popular then the other examples (at least labwc and liri) when you try to estimate the popularity using the number of packages on [repology](https://repology.org/).

**Comment by nesper8** [comment]
About wayfire, it's already mentioned in Compiz Support

**Comment by nesper8** [comment]
im thinking about closing this and redoing this PR from current master for the sake of correcting many mistakes

**Comment by wiki-me** [comment]
I think it's worth putting it in there twice, once under compiz and once under stacking windows managers, these are both very relevant issues.

**Pull request closed without merging**
